---
apiVersion: awx.ansible.com/v1beta1
kind: AWXBackup
metadata:
  name: awxbackup-2024-01-03
  namespace: awx-demo
spec:
  deployment_name: awx
  backup_pvc: awx-backup-claim

  # Uncomment to reveal "censored" logs
  #no_log: false