---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pv1-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  selector:
    matchLabels:
      purpose: backup-pv
