---
apiVersion: awx.ansible.com/v1beta1
kind: AWXRestore
metadata:
  name: awx-restore-2024-01-31
  namespace: awx-demo
spec:
  deployment_name: awx

  # Parameters to restore from AWXBackup object
  backup_name: awxbackup-2024-01-16

  # Parameters to restore from existing files on PVC (without AWXBackup object)
  # This needs testing on a brand new instance with no existing AWXBackup being ran on it.
  #backup_pvc: backup-pv1-claim
  #backup_dir: /data/backup

  # Uncomment to reveal "censored" logs
  no_log: false