---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx-demo

images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.9.0

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: awx-secret-tls
    type: kubernetes.io/tls
    files:
      - tls.crt
      - tls.key

  - name: awx-custom-certs
    files:
      - bundle-ca.crt=cacert.pem
    options:
      disableNameSuffixHash: true

  - name: awx-postgres-configuration
    type: Opaque
    literals:
      - host=awx-postgres-13
      - port=5432
      - database=awx
      - username=awx
      - password=Ansible123!
      - type=managed

  - name: awx-admin-password
    type: Opaque
    literals:
      - password=Ansible123!



  - name: awx-custom-secret-key
    type: Opaque
    literals:
    - secret_key=MySuperSecureSecretKey123!

resources:
  - github.com/ansible/awx-operator/config/default?ref=2.9.0
  - pv.yml
  - pvc.yml
  - awx.yml

