---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx-demo

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: awx-admin-password
    type: Opaque
    literals:
      - password=Ansible123!

  - name: awx-custom-secret-key
    type: Opaque
    literals:
      - secret_key=MySuperSecureSecretKey123!

resources:
  - awx-demo.yml
  - pv.yml
