---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx-demo
spec:
  admin_user: admin
  admin_password_secret: awx-admin-password
  secret_key_secret: awx-custom-secret-key

  ingress_type: ingress
  hostname: awx-demo.example.com
