---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx-demo

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.9.0

secretGenerator:
  - name: awx-admin-password
    type: Opaque
    literals:
    - password=Ansible123!

  - name: awx-custom-secret-key
    type: Opaque
    literals:
      - secret_key=MySuperSecureSecretKey123!

resources:
  - github.com/ansible/awx-operator/config/default?ref=2.9.0
  - awx-demo.yml
