---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Specify a custom namespace in which to install AWX
namespace: awx-demo

generatorOptions:
  disableNameSuffixHash: true

resources:
  - awx-demo-patched.yml
  - awx_admin_password_patch.yml

patches:
  - path: awx_admin_password_patch.yml
    target:
      kind: Secret
      name: awx-admin-password
