---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-pv2
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/pv0002/

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-pv3
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/pv0003/

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-pv4
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/pv0004/

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-pv5
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/pv0005/
  storageClassName: my-local-storage
