---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  ingress_type: ingress
  hostname: awx-demo.example.com
  admin_user: admin
  admin_password_secret: awx-admin-password
  secret_key_secret: awx-custom-secret-key
